app.url=https://auth.eagleeyenetworks.com/login
environment=QA
browser=chrome
headless=false
maximize=true
implicit.wait=5
explicit.wait=10
page.load.timeout=30
report.path=target/ExtentReport.html
screenshot.path=target/screenshots/
highlight.element=true
take.screenshot.on.pass=false
take.screenshot.on.fail=true